### ISSUE TITLE
PEP 249 exceptions: support DatabaseError subclasses whenever possible

### ISSUE THREAD

**Issue by fdcastel** [FirebirdSQL/python3-driver#35]
From [PEP 249](https://peps.python.org/pep-0249/#exceptions):

[DataError](https://peps.python.org/pep-0249/#dataerror)
Exception raised for errors that are due to problems with the processed data like division by zero, numeric value out of range, etc. 

[IntegrityError](https://peps.python.org/pep-0249/#integrityerror)
Exception raised when the relational integrity of the database is affected, e.g. a foreign key check fails. 

[InternalError](https://peps.python.org/pep-0249/#internalerror)
Exception raised when the database encounters an internal error, e.g. the cursor is not valid anymore, the transaction is out of sync, etc. 

[ProgrammingError](https://peps.python.org/pep-0249/#programmingerror)
Exception raised for programming errors, e.g. table not found or already exists, syntax error in the SQL statement, wrong number of parameters specified, etc. 

[NotSupportedError](https://peps.python.org/pep-0249/#notsupportederror)
Exception raised in case a method or database API was used which is not supported by the database, e.g. requesting a [.rollback()](https://peps.python.org/pep-0249/#id9) on a connection that does not support transaction or has transactions turned off.

**Comment by fdcastel** [comment]
Rationale: SQLAlchemy [can use](https://github.com/sqlalchemy/sqlalchemy/blob/99da5ebab36da61b7bfa0b868f50974d6a4c4655/lib/sqlalchemy/testing/requirements.py#L805) these more specific exceptions.

**Comment by pcisar** [comment]
Well, the problem is that firebird-driver does not know the exact cause for the error that is reported by Firebird OO API. The OO API reports error via Status that is part of all API calls. firebird-driver uses simple handling (for speed) that checks the Status and is there is an error, it raises exception with information taken from status. To provide any specific exception, firebird-driver will must implement some deeper analysis of Status error data and mapping to specific exceptions. Quite a lot of work + burden to maintain up to date.
