### ISSUE TITLE
Why not create python firebird libraries that not use C compiler or fbclient library pure python library 

### ISSUE THREAD

**Issue by arjuntpoyilil** [FirebirdSQL/python3-driver#39]
i know we got  firebirdsql but it is not open source and not further support and we are unable to use firebird in was lambda because of it has python3-driver has dependences outside python 

Need pure python library

**Comment by pcisar** [comment]
First, firebirdsql driver is open source! See https://github.com/nakagami/pyfirebirdsql/
Secondly, in the past I had considered introducing an abstract connectivity layer into firebird-driver, so users could choose whether they want to use OO API one or full native via network protocol. It turned out it would require too many hard compromises or to become too complicated. Hence I rejected the idea. It will be a nightmare to develop and specially to maintain. So, we ended with two drivers, and as long as Hajime Nakagami will maintain the firebirdsql, I'll not start another Python driver project under Firebird Project umbrella.
So, if you are not satisfied with current state of firebirdsql driver, I'd suggest to contact @nakagami about your problems, best via https://github.com/nakagami/pyfirebirdsql/issues
