### ISSUE TITLE
connect timeout

### ISSUE THREAD

**Issue by ml31415** [FirebirdSQL/python3-driver#42]
I regularly run into the issue, that if the server I'm trying to connect with, is temporarily unavailable, the `connect` function hangs for an eternity and doesn't even want to get interrupted from the keyboard. There is also no easy option, to set a timeout. Both things should be fixed imho.

**Comment by pcisar** [comment]
Well, it looks like problem in your networking setup. Did you checked TCP/IP configuration for connection timeout (i.e. how long systems try to establish a connection)?
Fixing this in driver, it's not possible, because it connects to database via OO API function that does not supports connection timeout. So until API function returns, there is no way how the driver can do anything.

**Comment by ml31415** [comment]
Yes, of course there is an issue with the network, if the server is not reachable. I'm talking about a solution for mitigation. A very standard and obvious one, which is unfortunately missing in `firebird-driver`.

Is there surely no way, to set a proper timeout, when the socket for the connection is set up?

**Comment by pcisar** [comment]
Once again. Driver uses Firebird client library via its OO API. The API function does not support timeouts, hence there is NO way how to handle this at driver level. If you think it's an omission on Firebird's side, file a ticket in Firebird itself, not the driver.
